# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pwd
          - ls -al
          - npm install @angular/cli -g
          - npm install
          - ng build --prod
    - step:
      name: Deploy to Webfaction
      deployment: test   # can be test, staging or production.
      # trigger: manual  # Uncomment to make this a manual deployment.
      script:
        - echo "Deploying to test environment - beta.fluxafya.com"
        - git push ssh:sisitec@web566.webfaction.com:/home/sisitec/webapps/fluxafya/.git HEAD