# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pwd
          - ls -al
          - npm install @angular/cli -g
          - ng config -g cli.warnings.versionMismatch false
          - npm install
          - ng build --prod
    - step:
        name: Deploy to test
        deployment: test
        script:
          - echo "Deploying to test environment - beta.fluxafya.com"
          - git push ssh://sisitec@web566.webfaction.com:/home/sisitec/webapps/fluxafya/.git HEAD -v
        